# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ad3b746518c33320656b5f1bf16604c4847b7d9468ca0524b23ee5fef3dc1203b2ecd2c3291f450b6f6451873058cbc63d51b95083af614b71e897065291191

test:
  secret_key_base: e911167b25cc88f6f7397f2d851b4f1ff75f0d99e01723cf265b49092d59008ac75f3b3d56947729aad484391c41b022275987b5d6ddbc6553c77db6de37d87b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
